import {
  Goal,
  Dumbbell,
  Waves,
  Trophy,
  Swords,
  Bike,
  Footprints,
  CircleDot,
  Star,
  Zap,
  Flame,
  Wind,
  Snowflake,
  Mountain,
  Target,
  Disc3,
  Flag,
  Shield,
  PersonStanding,
  Megaphone,
  Sailboat,
  Medal,
  Grip,
} from "lucide-react";

const sportIconMap: Record<string, any> = {
  goal: Goal,
  basketball: CircleDot,
  baseball: Trophy,
  waves: Waves,
  tennis: Zap,
  flip: Star,
  football: Dumbbell,
  volleyball: Flame,
  run: Footprints,
  dance: Wind,
  martial: Swords,
  hockey: Bike,
  wrestling: PersonStanding,
  cheerleading: Megaphone,
  softball: Medal,
  crosscountry: Footprints,
  lacrosse: Target,
  golf: Flag,
  skateboarding: Grip,
  cycling: Bike,
  skiing: Snowflake,
  rugby: Shield,
  fieldhockey: Goal,
  surfing: Sailboat,
  climbing: Mountain,
  tumbling: Star,
  equestrian: Wind,
  bowling: Disc3,
  frisbee: Disc3,
  tabletennis: Zap,
};

export function getSportIcon(iconName: string) {
  return sportIconMap[iconName] || Star;
}
