import { db } from "./db";
import { sports, leagues, programs } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const existingSports = await db.select().from(sports);
  if (existingSports.length > 0) return;

  const sportsData = [
    { name: "Soccer", icon: "goal", category: "Team Sports" },
    { name: "Basketball", icon: "basketball", category: "Team Sports" },
    { name: "Baseball", icon: "baseball", category: "Team Sports" },
    { name: "Football", icon: "football", category: "Team Sports" },
    { name: "Volleyball", icon: "volleyball", category: "Team Sports" },
    { name: "Track & Field", icon: "run", category: "Individual Sports" },
    { name: "Swimming", icon: "waves", category: "Individual Sports" },
    { name: "Gymnastics", icon: "flip", category: "Individual Sports" },
    { name: "Tennis", icon: "tennis", category: "Individual Sports" },
    { name: "Wrestling", icon: "wrestling", category: "Individual Sports" },
    { name: "Cheerleading", icon: "cheerleading", category: "Arts & Performance" },
    { name: "Dance", icon: "dance", category: "Arts & Performance" },
    { name: "Martial Arts", icon: "martial", category: "Individual Sports" },
    { name: "Ice Hockey", icon: "hockey", category: "Team Sports" },
    { name: "Softball", icon: "softball", category: "Team Sports" },
    { name: "Cross Country Running", icon: "crosscountry", category: "Individual Sports" },
    { name: "Lacrosse", icon: "lacrosse", category: "Team Sports" },
    { name: "Golf", icon: "golf", category: "Individual Sports" },
    { name: "Skateboarding", icon: "skateboarding", category: "Individual Sports" },
    { name: "Cycling / BMX", icon: "cycling", category: "Individual Sports" },
    { name: "Skiing / Snowboarding", icon: "skiing", category: "Winter Sports" },
    { name: "Rugby", icon: "rugby", category: "Team Sports" },
    { name: "Field Hockey", icon: "fieldhockey", category: "Team Sports" },
    { name: "Surfing", icon: "surfing", category: "Water Sports" },
    { name: "Rock Climbing / Bouldering", icon: "climbing", category: "Individual Sports" },
    { name: "Cheer & Tumbling / Acrobatics", icon: "tumbling", category: "Arts & Performance" },
    { name: "Equestrian / Horseback Riding", icon: "equestrian", category: "Individual Sports" },
    { name: "Bowling", icon: "bowling", category: "Individual Sports" },
    { name: "Ultimate Frisbee", icon: "frisbee", category: "Team Sports" },
    { name: "Table Tennis", icon: "tabletennis", category: "Individual Sports" },
  ];

  const insertedSports = await db.insert(sports).values(sportsData).returning();
  const sportMap = Object.fromEntries(insertedSports.map(s => [s.name, s.id]));

  const leaguesData = [
    {
      name: "Riverside Youth Athletics",
      description: "Serving the community for over 25 years with quality youth sports programs. Our experienced coaches focus on skill development, teamwork, and fun.",
      website: "https://riversideyouth.example.com",
      phone: "(555) 234-5678",
      email: "info@riversideyouth.com",
      city: "Riverside",
      state: "CA",
      zipCode: "92501",
      logoUrl: null,
      rating: 45,
      reviewCount: 128,
    },
    {
      name: "Metro Parks & Recreation",
      description: "City-sponsored recreation programs for all ages. Affordable pricing with a focus on making sports accessible to every family.",
      website: "https://metroparks.example.com",
      phone: "(555) 345-6789",
      email: "sports@metroparks.gov",
      city: "Springfield",
      state: "IL",
      zipCode: "62701",
      logoUrl: null,
      rating: 42,
      reviewCount: 256,
    },
    {
      name: "All-Star Youth League",
      description: "Competitive and recreational leagues for aspiring athletes. Professional-grade facilities and USSF-certified coaches.",
      website: "https://allstaryouth.example.com",
      phone: "(555) 456-7890",
      email: "register@allstaryouth.com",
      city: "Austin",
      state: "TX",
      zipCode: "78701",
      logoUrl: null,
      rating: 48,
      reviewCount: 312,
    },
    {
      name: "Lakeside Community Sports",
      description: "Family-friendly youth sports with emphasis on participation and personal growth. Every child plays, every child matters.",
      website: "https://lakesidesports.example.com",
      phone: "(555) 567-8901",
      email: "hello@lakesidesports.com",
      city: "Portland",
      state: "OR",
      zipCode: "97201",
      logoUrl: null,
      rating: 47,
      reviewCount: 189,
    },
    {
      name: "Champions Athletic Club",
      description: "Elite training programs with a path from recreational to competitive play. State-of-the-art indoor and outdoor facilities.",
      website: "https://championsac.example.com",
      phone: "(555) 678-9012",
      email: "enroll@championsac.com",
      city: "Denver",
      state: "CO",
      zipCode: "80201",
      logoUrl: null,
      rating: 46,
      reviewCount: 174,
    },
  ];

  const insertedLeagues = await db.insert(leagues).values(leaguesData).returning();

  const programsData = [
    {
      leagueId: insertedLeagues[0].id,
      sportId: sportMap["Soccer"],
      name: "Spring Soccer - Under 8",
      description: "Introductory soccer program focused on basic skills, dribbling, passing, and having fun. Games on Saturday mornings.",
      ageMin: 5,
      ageMax: 8,
      gender: "coed",
      season: "Spring 2026",
      registrationOpen: "2026-02-15",
      registrationClose: "2026-03-15",
      programStart: "2026-04-01",
      programEnd: "2026-06-15",
      cost: 125,
      maxParticipants: 60,
      spotsLeft: 23,
      location: "Riverside Community Park",
    },
    {
      leagueId: insertedLeagues[0].id,
      sportId: sportMap["Soccer"],
      name: "Spring Soccer - Under 12",
      description: "Intermediate soccer with more advanced tactics and positions. Two practices per week plus Saturday games.",
      ageMin: 9,
      ageMax: 12,
      gender: "coed",
      season: "Spring 2026",
      registrationOpen: "2026-02-15",
      registrationClose: "2026-03-15",
      programStart: "2026-04-01",
      programEnd: "2026-06-15",
      cost: 150,
      maxParticipants: 48,
      spotsLeft: 12,
      location: "Riverside Sports Complex",
    },
    {
      leagueId: insertedLeagues[1].id,
      sportId: sportMap["Basketball"],
      name: "Youth Basketball League",
      description: "Recreation basketball for kids of all skill levels. Learn fundamentals and play in weekly games at the community gym.",
      ageMin: 6,
      ageMax: 10,
      gender: "coed",
      season: "Spring 2026",
      registrationOpen: "2026-03-01",
      registrationClose: "2026-03-25",
      programStart: "2026-04-05",
      programEnd: "2026-06-20",
      cost: 95,
      maxParticipants: 80,
      spotsLeft: 45,
      location: "Metro Community Center Gym",
    },
    {
      leagueId: insertedLeagues[1].id,
      sportId: sportMap["Swimming"],
      name: "Summer Swim Team",
      description: "Competitive and recreational swim team. Daily practices with weekend meets. All stroke levels welcome.",
      ageMin: 5,
      ageMax: 14,
      gender: "coed",
      season: "Summer 2026",
      registrationOpen: "2026-04-01",
      registrationClose: "2026-05-15",
      programStart: "2026-06-01",
      programEnd: "2026-08-15",
      cost: 200,
      maxParticipants: 100,
      spotsLeft: 67,
      location: "Metro Aquatic Center",
    },
    {
      leagueId: insertedLeagues[2].id,
      sportId: sportMap["Baseball"],
      name: "Spring T-Ball",
      description: "Perfect introduction to baseball for the youngest players. Focus on batting, catching, and base running in a fun environment.",
      ageMin: 4,
      ageMax: 6,
      gender: "coed",
      season: "Spring 2026",
      registrationOpen: "2026-02-20",
      registrationClose: "2026-03-20",
      programStart: "2026-04-01",
      programEnd: "2026-06-01",
      cost: 85,
      maxParticipants: 40,
      spotsLeft: 8,
      location: "All-Star Field Complex",
    },
    {
      leagueId: insertedLeagues[2].id,
      sportId: sportMap["Baseball"],
      name: "Youth Baseball - Minors",
      description: "Coach-pitch and player-pitch baseball for developing players. Emphasis on fundamentals and sportsmanship.",
      ageMin: 7,
      ageMax: 10,
      gender: "coed",
      season: "Spring 2026",
      registrationOpen: "2026-02-20",
      registrationClose: "2026-03-20",
      programStart: "2026-04-01",
      programEnd: "2026-06-30",
      cost: 135,
      maxParticipants: 60,
      spotsLeft: 18,
      location: "All-Star Field Complex",
    },
    {
      leagueId: insertedLeagues[3].id,
      sportId: sportMap["Tennis"],
      name: "Junior Tennis Academy",
      description: "Learn tennis from certified instructors. Small group lessons with match play. Equipment provided for beginners.",
      ageMin: 6,
      ageMax: 14,
      gender: "coed",
      season: "Spring 2026",
      registrationOpen: "2026-03-01",
      registrationClose: "2026-04-01",
      programStart: "2026-04-15",
      programEnd: "2026-06-30",
      cost: 175,
      maxParticipants: 32,
      spotsLeft: 14,
      location: "Lakeside Tennis Courts",
    },
    {
      leagueId: insertedLeagues[3].id,
      sportId: sportMap["Gymnastics"],
      name: "Tumbling & Gymnastics",
      description: "Recreational gymnastics for beginners and intermediate students. Build strength, flexibility, and coordination.",
      ageMin: 4,
      ageMax: 10,
      gender: "coed",
      season: "Spring 2026",
      registrationOpen: "2026-02-15",
      registrationClose: "2026-03-10",
      programStart: "2026-03-20",
      programEnd: "2026-06-15",
      cost: 160,
      maxParticipants: 24,
      spotsLeft: 5,
      location: "Lakeside Gymnastics Center",
    },
    {
      leagueId: insertedLeagues[4].id,
      sportId: sportMap["Football"],
      name: "Flag Football League",
      description: "Non-contact flag football focusing on skills, strategy, and teamwork. Perfect for kids who love football in a safe environment.",
      ageMin: 6,
      ageMax: 12,
      gender: "coed",
      season: "Fall 2026",
      registrationOpen: "2026-07-01",
      registrationClose: "2026-08-15",
      programStart: "2026-09-01",
      programEnd: "2026-11-15",
      cost: 110,
      maxParticipants: 72,
      spotsLeft: 72,
      location: "Champions Sports Complex",
    },
    {
      leagueId: insertedLeagues[4].id,
      sportId: sportMap["Dance"],
      name: "Creative Dance for Kids",
      description: "Explore movement and rhythm through creative dance. Includes ballet basics, jazz, and modern dance styles.",
      ageMin: 4,
      ageMax: 8,
      gender: "coed",
      season: "Spring 2026",
      registrationOpen: "2026-02-25",
      registrationClose: "2026-03-20",
      programStart: "2026-04-01",
      programEnd: "2026-06-15",
      cost: 140,
      maxParticipants: 20,
      spotsLeft: 9,
      location: "Champions Dance Studio",
    },
    {
      leagueId: insertedLeagues[0].id,
      sportId: sportMap["Track & Field"],
      name: "Junior Track Club",
      description: "Introduction to track and field events including sprints, distance running, long jump, and shot put.",
      ageMin: 7,
      ageMax: 14,
      gender: "coed",
      season: "Spring 2026",
      registrationOpen: "2026-03-01",
      registrationClose: "2026-03-30",
      programStart: "2026-04-10",
      programEnd: "2026-06-20",
      cost: 90,
      maxParticipants: 50,
      spotsLeft: 32,
      location: "Riverside High School Track",
    },
    {
      leagueId: insertedLeagues[2].id,
      sportId: sportMap["Martial Arts"],
      name: "Kids Karate - Beginner",
      description: "Traditional karate instruction focusing on discipline, respect, and self-defense. Belt progression system included.",
      ageMin: 5,
      ageMax: 12,
      gender: "coed",
      season: "Year-Round",
      registrationOpen: "2026-01-01",
      registrationClose: "2026-12-31",
      programStart: "2026-03-01",
      programEnd: "2026-08-31",
      cost: 120,
      maxParticipants: 30,
      spotsLeft: 15,
      location: "All-Star Martial Arts Dojo",
    },
    {
      leagueId: insertedLeagues[1].id,
      sportId: sportMap["Volleyball"],
      name: "Girls Volleyball Camp",
      description: "Skill-building volleyball camp with focus on serving, setting, passing, and teamwork. Led by experienced high school coaches.",
      ageMin: 8,
      ageMax: 14,
      gender: "female",
      season: "Summer 2026",
      registrationOpen: "2026-04-15",
      registrationClose: "2026-06-01",
      programStart: "2026-06-15",
      programEnd: "2026-07-31",
      cost: 155,
      maxParticipants: 36,
      spotsLeft: 28,
      location: "Metro Sports Arena",
    },
    {
      leagueId: insertedLeagues[4].id,
      sportId: sportMap["Soccer"],
      name: "Summer Soccer Camp",
      description: "Intensive week-long soccer camp with professional coaching. Morning sessions with games and tournaments on Friday.",
      ageMin: 7,
      ageMax: 14,
      gender: "coed",
      season: "Summer 2026",
      registrationOpen: "2026-04-01",
      registrationClose: "2026-05-30",
      programStart: "2026-06-15",
      programEnd: "2026-06-20",
      cost: 195,
      maxParticipants: 50,
      spotsLeft: 38,
      location: "Champions Sports Complex",
    },
  ];

  await db.insert(programs).values(programsData);
  console.log("Database seeded successfully");
}
